# Generated by Django 4.2.16 on 2024-11-15 15:56

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athleterequest',
            name='programming_deadline',
            field=models.DateField(default=users.models.default_programming_deadline),
        ),
    ]
