# Generated by Django 4.2.16 on 2024-11-21 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_athleterequest_programming_deadline'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date_posted', models.DateField()),
                ('url', models.URLField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='users.athletedocument')),
            ],
        ),
    ]
